### ISSUE TITLE
website: category reorganization suggestion

### ISSUE THREAD

**Issue by oliverpool** [gokrazy/gokrazy#126]
I find it great that so much is documented on the [gokrazy website](https://gokrazy.org)

However I find the current section ordering a bit counter-intuitive:

```
1. Showcase
2. Quickstart
3. Userguide
  - input/output
  - package config
  - process interface
  - remote syslog
  - TLS
  - wifi
  - bluetooth
  - go modules
  - Access permanent data
  - How do I install X on gokrazy (tailscale / caddy / Min.io)
4. Hardware and CI
5. Non-Go Prototyping
```

The resources to install an existing package (`how do I install X`), to configure gokrazy (`package config`, `wifi`) and to develop a new package (`process interface`, `bluethooth`, `Non-Go Prototyping`) are interleaved.

---

I would suggest to reorganize the categories, based on the usage : available packages / packaging existing / developing a new package.

For instance:
```
1. Quickstart (unchanged)
2. Supported platforms (Hardware and CI)
3. Configuration
  - package config (unchanged)
  - remote syslog (unchanged)
  - TLS (unchanged)
  - wifi (unchanged)
  - Access permanent data (unchanged)
4. Available packages (Showcase)
  - tailscale (unchanged)
  - caddy (unchanged)
  - min.io (unchanged)
5. Packaging new software (Non-Go Prototyping)
5. Package development
  - input/output (unchanged)
  - process interface (unchanged)
  - bluetooth (unchanged)
  - go modules (unchanged)
 ```

What do you think? I could make a PR, if you think that this would be an improvement (can hugo handle redirects, to prevent 404s?).

**Comment by stapelberg** [comment]
Thanks for making this suggestion! The documentation has grown historically, so it’s always good to think about more structure from time to time.

In general, your suggested structure seems fine to me. I have a few notes though:

* In “Available packages”, I think we should make “Showcase” a sub page under “Available packages”, and have the top-level “Available packages” be an index (like https://gokrazy.org/userguide/ currently is).
* The “Packaging new software” section should keep its current name “Non-Go Prototyping”. Otherwise it might invoke the impression that packaging external software is an intended use-case, when it’s supposed to be a stop-gap.
* I’m not 100% sure whether bluetooth belongs into package development or into configuration (just like wifi). It’s not strictly only for development — maybe you want to just install an existing bluetooth-low-energy-sensor-to-prometheus program?

Hugo supports specifying aliases so that existing URLs keep working. Ideally your PR would change as few URLs as possible though :)
