### ISSUE TITLE
Netboot support

### ISSUE THREAD

**Issue by biemster** [gokrazy/gokrazy#135]
Great project! I've been using Alpine Linux to create minimal systems on RPi4, and boot them over the network using TFTP and HTTP. I've automated this here: https://github.com/biemster/rpi4_alpine_netboot

Especially the netboot is a feature I value a lot, and I will move at least some if not all of my boards to gokrazy if that can do it too. Is this also in the planning for gokrazy?

**Comment by stapelberg** [comment]
Thanks for your interest!

Netbooting is not currently planned for gokrazy. We want to primarily stick with the most common deployment mechanism, which is SD cards. Already when using USB memory sticks, I have run into different bugs than with running from SD card, so I’m not saying this out of exaggerated caution — if we wanted to support netboot, we’d need to do it in addition to supporting SD cards, effectively doubling the size of our already large enough test matrix (see https://gokrazy.org/platforms/), which is a concern.

An advantage of having local storage in each Raspberry Pi is that each Pi is a separate failure domain, compared to a netboot setup where any issues with your central netboot server might mean that one or more Pis no longer work. In my network(s), I like making failure domains as specific as possible for maximum reliability.

I had a look at your alpine setup, and it seems like the entire alpine system is running from the initramfs. gokrazy on the other hand doesn’t even have an initramfs (there was no need to have one thus far).

(Also, gokrazy’s A/B partition updating scheme would need to be re-thought/adapted for a netboot scenario.)

That said, even if the feature is not officially supported, if you’re motivated to investigate and possibly contribute netboot support, I don’t mind at least reviewing any changes to make netboot support easier. I can’t guarantee that the patches can all be merged, though, because I don’t want to unduly burden the project in terms of complexity and required changes for existing devices.
